# Generated by Django 5.2.1 on 2025-05-16 07:10
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_library', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
